### ISSUE TITLE
Maybe use try with resources 

### ISSUE THREAD

**Issue by edigitman** [EcaterinaA/Donation#7]
https://github.com/EcaterinaA/Donation/blob/78486e8460a1adae4844bcbc5b81c5d44b02b029/src/main/java/ro/ecaterina/donation/dao/UserDao.java#L51

https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by EcaterinaA** [comment]
Done it!

**Comment by EcaterinaA** [comment]
![image](https://user-images.githubusercontent.com/66332896/92412406-758dde00-f154-11ea-9d60-d3aca891a292.png)
